# Site settings
title: Jason C. Richardson
email: jcrichardson617@gmail.com
description: ""

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jcrichardson617.github.io" # the base hostname & protocol for your site
linkedin_username: jcrichardson617
github_username:  jcrichardson617

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jemoji
  
analytics:
      		provider: "google-universal"
  google:
 	tracking_id: "UA-1234567-8"

plugins:
  - jekyll-seo-tag
